app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:postgresql://13.74.185.80:5432/appdb

service:
  workingdir: "/home/cinitron/spring"
  execstart: "java -jar target/demo-0.0.1-SNAPSHOT.jar"
