- hosts: all
  tasks:
    - name: Add Docker's official GPG key
      become: yes
      become_user: root
      shell: |
        apt-get update 
        apt-get install ca-certificates curl
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add the repository to Apt sources
      become: yes
      become_user: root
      shell: | 
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        
    - name: remove frontend lock that prevents installing docker
      become: yes
      become_user: root
      command: rm /var/lib/dpkg/lock-frontend

        
    - name: Install docker
      become: yes
      become_user: root
      command: apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin 
      
    - name: Install docker-compose
      become: yes
      become_user: root
      command: apt-get -y install docker-compose
      
    - name: "debug appdir"
      ansible.builtin.debug:
        msg: "appdir {{ansible_user_dir}}"
              
    - name: "Clone the Spring repository"
      git:
        repo: "https://github.com/VasileiosKokki/FarmerCompensation_University.git"
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes
        
    - name: Stop existing Docker Compose services
      command: docker-compose down
      args:
        chdir: "{{ appdir }}"
      ignore_errors: true
      tags: backend
                   
    - name: Build Docker Compose without services
      become: yes
      become_user: root
      docker_compose:
        project_src: "{{ appdir }}"
        state: absent
        build: yes
      tags: backend
      
    - name: Start Docker Compose services
      become: yes
      become_user: root
      docker_compose:
        project_src: "{{ appdir }}"
        state: present
      tags: backend
     
      
     





      
